// Browser E2E. Requires Playwright and its Chromium browser; uses disposable server data.
const {chromium}=require('playwright');
const {spawn}=require('node:child_process');
const fs=require('node:fs');
const path=require('node:path');
const os=require('node:os');
const assert=require('node:assert/strict');
const classes=path.resolve(process.argv[2]||'bin');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'platform-browser-'));
fs.symlinkSync(path.resolve('web'),path.join(tmp,'web'),'dir');
const server=spawn('java',['-cp',classes,'server.ParkingServer'],{cwd:tmp,env:{...process.env,PLATFORM_DEMO:'true',PLATFORM_DATA_DIR:path.join(tmp,'platform')},stdio:'ignore'});
(async()=>{
 let browser, onboardingServer;
 try {
  for(let i=0;i<100;i++){try{const r=await fetch('http://localhost:8080/api/platform/state');if(r.status===401)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000}}), errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('dialog',d=>d.accept());
  await page.goto('http://localhost:8080/platform.html');
  await page.locator('#loginForm [name=username]').fill('owner');
  await page.locator('#loginForm [name=password]').fill('DemoPass123!');
  await page.locator('#loginForm button').click();
  await page.locator('#workspace').waitFor({state:'visible'});
  await page.screenshot({path:path.join(tmp,'platform-desktop.png'),fullPage:true});
  await page.locator('[data-action=editSite]').first().click();
  await page.locator('[data-action=publish]').click();
  await page.locator('#notice').filter({hasText:'เผยแพร่ผังแล้ว'}).waitFor();
  await page.locator('[data-nav=operations]').click();
  await page.locator('[data-action=checkin]').click();
  await page.locator('#modal [name=plate]').fill('BROWSER-01');
  await page.locator('#modal [name=slotId]').selectOption('A4');
  await page.locator('#modal button[type=submit]').click();
  await page.locator('#modal').waitFor({state:'hidden'});
  assert(await page.locator('tbody').innerText().then(t=>t.includes('BROWSER-01')));
  // The main dashboard shares this session, site state, and ledger with the editor.
  await page.goto('http://localhost:8080/dashboard.html');
  await page.locator('#workspace').waitFor({state:'visible'});
  assert(await page.locator('#slotMap').innerText().then(t=>t.includes('BROWSER-01')));
  assert((await page.locator('.brand').innerText()).includes('Smart Parking System'));
  assert((await page.locator('#boardMessage').innerText()).includes('ว่าง'));
  await page.locator('[data-slot=A6]').click();
  assert.equal(await page.locator('#entryForm [name=slotId]').inputValue(),'A6');
  await page.locator('[data-tab=map]').click();
  await page.screenshot({path:path.join(tmp,'dashboard-reference-desktop.png'),fullPage:true});
  await page.locator('[data-tab=exit]').click();
  await page.locator('[data-exit]').click();
  await page.locator('#notice').filter({hasText:'บันทึกรถออกแล้ว'}).waitFor();
  await page.locator('[data-tab=ledger]').click();
  assert((await page.locator('#ledgerTable').innerText()).includes('BROWSER-01'));
  await page.locator('[data-tab=members]').click();
  await page.locator('#memberForm [name=name]').fill('Dashboard member');
  await page.locator('#memberForm [name=plate]').fill('DASH-MEMBER');
  await page.locator('#memberForm [name=room]').fill('D101');
  await page.locator('#memberForm [name=starts]').fill('2026-01-01');
  await page.locator('#memberForm [name=expires]').fill('2030-12-31');
  await page.locator('#memberForm button').click();
  await page.locator('#membersTable').getByText('Dashboard member').waitFor();
  await page.locator('[data-tab=reservations]').click();
  await page.locator('#reservationForm [name=plate]').fill('DASH-BOOKING');
  await page.locator('#reservationForm [name=slotId]').selectOption('A6');
  await page.locator('#reservationForm [name=from]').fill('2030-12-01T10:00');
  await page.locator('#reservationForm [name=to]').fill('2030-12-01T11:00');
  await page.locator('#reservationForm button').click();
  await page.locator('#reservationsTable').getByText('DASH-BOOKING').waitFor();
  await page.locator('[data-cancel]').click();
  await page.locator('#notice').filter({hasText:'ยกเลิกการจองแล้ว'}).waitFor();
  await page.locator('[data-tab=revenue]').click();
  assert(Number(await page.locator('#dailyDeparted').innerText())>=1);
  await page.setViewportSize({width:390,height:844});
  await page.locator('[data-tab=map]').click();
  await page.screenshot({path:path.join(tmp,'dashboard-reference-mobile.png'),fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.setViewportSize({width:1440,height:1000});
  await page.goto('http://localhost:8080/platform.html');
  await page.locator('#workspace').waitFor({state:'visible'});
  await page.locator('[data-action=openSite]').first().click();
  await page.locator('[data-nav=history]').click();
  const downloading=page.waitForEvent('download');
  await page.locator('[data-action=export]').click();
  const download=await downloading; await download.saveAs(path.join(tmp,'history.xlsx'));
  assert(fs.statSync(path.join(tmp,'history.xlsx')).size>1000);
  await page.locator('[data-nav=sites]').click();
  await page.locator('[data-action=createSite]').click();
  await page.locator('#modal [name=name]').fill('Browser custom');
  await page.locator('#modal [name=businessType]').selectOption('CUSTOM');
  await page.locator('#modal button[type=submit]').click();
  await page.locator('#modal').waitFor({state:'hidden'});
  for(const [type,x,y]of [['ENTRY',0,0],['ROAD',1,0],['EXIT',2,0],['SLOT',1,1]]){
   await page.locator(`[data-tool=${type}]`).click();
   await page.locator(`.cell[data-x="${x}"][data-y="${y}"]`).click();
  }
  await page.locator('[data-action=publish]').click();
  await page.locator('#notice').filter({hasText:'เผยแพร่ผังแล้ว'}).waitFor();
  await page.screenshot({path:path.join(tmp,'platform-editor.png'),fullPage:true});
  for(const nav of ['members','devices','settings','users','audit'])await page.locator(`[data-nav=${nav}]`).click();
  await page.locator('[data-nav=settings]').click();
  await page.locator('[data-action=pricing]').click();
  await page.locator('#modal [name=memberDiscountPercent]').fill('50');
  await page.locator('#modal [name=roomQuota]').fill('2');
  await page.locator('#modal button[type=submit]').click();
  await page.locator('#modal').waitFor({state:'hidden'});
  await page.locator('[data-nav=members]').click();
  assert((await page.locator('#main').innerText()).includes('50%'));
  await page.locator('[data-nav=editor]').click();
  await page.locator('[data-action=roadCurve]').click();
  await page.locator('#modal [name=label]').fill('Test curved road');
  await page.locator('#modal button[type=submit]').click();
  await page.locator('#modal').waitFor({state:'hidden'});
  assert.equal(await page.locator('svg[aria-label="แบบร่างถนนโค้ง"] path').count(),2);
  await page.setViewportSize({width:390,height:844});
  await page.locator('[data-nav=sites]').click();
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:path.join(tmp,'platform-mobile.png'),fullPage:true});
  await page.locator('#logoutButton').click();
  await page.locator('#loginScreen').waitFor({state:'visible'});
  await page.locator('#loginForm [name=username]').fill('staff');
  await page.locator('#loginForm [name=password]').fill('DemoPass123!');
  await page.locator('#loginForm button').click();
  await page.locator('#workspace').waitFor({state:'visible'});
  assert.equal(await page.locator('[data-nav=editor]').count(),0);
  assert.equal(await page.locator('[data-nav=history]').count(),0);
  await page.goto('http://localhost:8080/dashboard.html');
  await page.locator('#workspace').waitFor({state:'visible'});
  assert.equal(await page.locator('#sitePicker option').count(),1);
  await page.locator('[data-tab=history]').click();
  assert.equal(await page.locator('#exportButton').isVisible(),false);
  await page.goto('http://localhost:8080/platform.html');
  await page.locator('#workspace').waitFor({state:'visible'});
  await page.getByRole('button',{name:'เปลี่ยนรหัสผ่าน',exact:true}).click();
  await page.locator('#modal [name=currentPassword]').fill('DemoPass123!');
  await page.locator('#modal [name=newPassword]').fill('BrowserPassword123!');
  await page.locator('#modal [name=confirmPassword]').fill('BrowserPassword123!');
  await page.locator('#modal button[type=submit]').click();
  await page.locator('#loginScreen').waitFor({state:'visible'});
  await page.locator('#loginForm [name=username]').fill('staff');
  await page.locator('#loginForm [name=password]').fill('BrowserPassword123!');
  await page.locator('#loginForm button').click();
  await page.locator('#workspace').waitFor({state:'visible'});
  assert.deepEqual(errors,[]);
  const onboardingDir=path.join(tmp,'production-onboarding');
  fs.mkdirSync(onboardingDir); fs.symlinkSync(path.resolve('web'),path.join(onboardingDir,'web'),'dir');
  onboardingServer=spawn('java',['-cp',classes,'server.ParkingServer'],{cwd:onboardingDir,env:{...process.env,PORT:'8081',PLATFORM_ONLY:'true',PLATFORM_DEMO:'false',PLATFORM_ADMIN_PASSWORD:'SandboxPassword123!',PLATFORM_DATA_DIR:path.join(onboardingDir,'platform')},stdio:'ignore'});
  for(let i=0;i<100;i++){try{const r=await fetch('http://localhost:8081/api/platform/health');if(r.ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  const onboarding=await browser.newPage(); onboarding.on('dialog',dialog=>dialog.accept());
  await onboarding.goto('http://localhost:8081/');
  assert(onboarding.url().endsWith('/dashboard.html'));
  await onboarding.goto('http://localhost:8081/platform.html');
  await onboarding.locator('#loginForm [name=username]').fill('superadmin');
  await onboarding.locator('#loginForm [name=password]').fill('SandboxPassword123!');
  await onboarding.locator('#loginForm button').click();
  await onboarding.locator('[data-action=sampleWorkspace]').waitFor();
  await onboarding.locator('[data-action=sampleWorkspace]').click();
  await onboarding.locator('#main .grid').waitFor();
  assert.equal(await onboarding.locator('#main .cell.SLOT').count(),20);
  await onboarding.locator('#floorPicker').selectOption('2');
  assert.equal(await onboarding.locator('#main .cell.SLOT').count(),20);
  await onboarding.locator('[data-nav=sites]').click();
  assert.equal(await onboarding.locator('.cards .card').count(),3);
  await onboarding.locator('[data-nav=history]').click();
  assert((await onboarding.locator('#main').innerText()).includes('ตัวอย่าง-'));
  await onboarding.locator('#backToCustomers').click();
  await onboarding.locator('[data-action=tenant]').click();
  await onboarding.locator('#modal [name=name]').fill('Isolated customer');
  await onboarding.locator('#modal [name=username]').fill('isolated-owner');
  await onboarding.locator('#modal [name=password]').fill('CustomerPassword123!');
  await onboarding.locator('#modal button[type=submit]').click();
  await onboarding.locator('#modal').waitFor({state:'hidden'});
  const customerRow=onboarding.locator('tr').filter({hasText:'Isolated customer'});
  await customerRow.locator('[data-action=enterTenant]').click();
  assert.equal(await onboarding.locator('.cards .card').count(),0);
  assert.equal(await onboarding.locator('#tenantContext').innerText(),'Isolated customer');
  await onboarding.locator('[data-action=createSite]').click();
  await onboarding.locator('#modal [name=name]').fill('Private customer lot');
  await onboarding.locator('#modal button[type=submit]').click();
  await onboarding.locator('#modal').waitFor({state:'hidden'});
  const dashboardLink=await onboarding.locator('a[href^="dashboard.html?"]').first().getAttribute('href');
  await onboarding.goto('http://localhost:8081/'+dashboardLink);
  await onboarding.locator('#workspace').waitFor({state:'visible'});
  assert.equal(await onboarding.locator('#sitePicker option').count(),1);
  assert((await onboarding.locator('#account').innerText()).includes('Isolated customer'));
  await onboarding.goto('http://localhost:8081/platform.html');
  await onboarding.locator('#logoutButton').click();
  await onboarding.locator('#loginForm [name=username]').fill('isolated-owner');
  await onboarding.locator('#loginForm [name=password]').fill('CustomerPassword123!');
  await onboarding.locator('#loginForm button').click();
  await onboarding.locator('#workspace').waitFor({state:'visible'});
  assert.equal(await onboarding.locator('[data-nav=customers]').count(),0);
  assert.equal(await onboarding.locator('[data-action=tenant]').count(),0);
  assert.equal(await onboarding.locator('#sitePicker option').count(),1);
  assert(!(await onboarding.locator('#main').innerText()).includes('Green Residence'));
  await onboarding.locator('[data-nav=users]').click();
  assert((await onboarding.locator('#main').innerText()).includes('isolated-owner'));
  assert(!(await onboarding.locator('#main').innerText()).includes('superadmin'));
  console.log('Browser PASS: shared dashboard session/ledger, parking, cash checkout, XLSX, custom road layout, all tabs, mobile, staff permissions');
  console.log('QA artifacts: '+tmp);
 } finally {if(process.env.CI){fs.mkdirSync('browser-artifacts',{recursive:true});for(const name of fs.readdirSync(tmp).filter(n=>n.endsWith('.png')))fs.copyFileSync(path.join(tmp,name),path.join('browser-artifacts',name));}if(browser)await browser.close();server.kill('SIGTERM');if(onboardingServer)onboardingServer.kill('SIGTERM');}
})().catch(e=>{console.error(e);process.exitCode=1;});
