// Browser E2E. Requires Playwright and its Chromium browser; uses disposable server data.
const {chromium}=require('playwright');
const {spawn}=require('node:child_process');
const fs=require('node:fs');
const path=require('node:path');
const os=require('node:os');
const assert=require('node:assert/strict');
const classes=path.resolve(process.argv[2]||'bin');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'platform-browser-'));
fs.symlinkSync(path.resolve('web'),path.join(tmp,'web'),'dir');
const server=spawn('java',['-cp',classes,'server.ParkingServer'],{cwd:tmp,env:{...process.env,PLATFORM_DEMO:'true',PLATFORM_DATA_DIR:path.join(tmp,'platform')},stdio:'ignore'});
(async()=>{
 let browser, onboardingServer;
 try {
  for(let i=0;i<100;i++){try{const r=await fetch('http://localhost:8080/api/platform/state');if(r.status===401)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000}}), errors=[];
  // Public HTTP origins lack randomUUID; localhost otherwise hides this regression.
  await page.addInitScript(() => Object.defineProperty(crypto, 'randomUUID', {value:undefined}));
  page.on('pageerror',e=>errors.push(e.message));
  page.on('dialog',d=>d.accept());
  await page.goto('http://localhost:8080/platform.html');
  await page.screenshot({animations:'disabled',path:path.join(tmp,'studio-login-desktop.png'),fullPage:true});
  await page.locator('.pricing-cta').filter({hasText:'Business'}).click();
  await page.locator('[data-demo-contact="LINE"]').click();
  assert((await page.locator('#contactPreview').innerText()).includes('990'));
  await page.locator('[data-demo-contact="อีเมล"]').click();
  assert((await page.locator('#contactPreview').innerText()).includes('ยังไม่ได้ส่งข้อความ'));
  await page.screenshot({animations:'disabled',path:path.join(tmp,'public-contact-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({animations:'disabled',path:path.join(tmp,'public-contact-mobile.png'),fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Contact page must fit mobile');
  await page.goto('http://localhost:8080/platform.html');
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('#loginForm [name=username]').fill('owner');
  await page.locator('#loginForm [name=password]').fill('DemoPass123!');
  await page.locator('#loginForm button[type=submit]').click();
  await page.locator('#workspace').waitFor({state:'visible'});
  await page.screenshot({animations:'disabled',path:path.join(tmp,'platform-desktop.png'),fullPage:true});
  await page.locator('[data-nav=users]').click();
  await page.locator('[data-action=user]').click();
  await page.locator('#modal [name=username]').fill('browser.employee');
  await page.locator('#modal [name=password]').fill('EmployeePass123!');
  assert.equal(await page.locator('#modal [name=role]').inputValue(),'staff');
  await page.locator('#modal [name=siteIds]').first().check();
  await page.locator('#modal button[type=submit]').click();
  await page.locator('#modal').waitFor({state:'hidden'});
  const employeeRow=page.locator('tr').filter({hasText:'browser.employee'});
  await employeeRow.locator('[data-action=editTeamUser]').click();
  await page.locator('#modal [name=role]').selectOption('admin');
  await page.locator('#modal button[type=submit]').click();
  await page.locator('#modal').waitFor({state:'hidden'});
  await employeeRow.locator('[data-action=resetTeamPassword]').click();
  await page.locator('#modal [name=newPassword]').fill('NewEmployee123!');
  await page.locator('#modal [name=confirmPassword]').fill('NewEmployee123!');
  await page.locator('#modal button[type=submit]').click();
  await page.locator('#modal').waitFor({state:'hidden'});
  await page.locator('[data-nav=sites]').click();
  await page.locator('[data-action=editSite]').first().click();
  const placed=[];
  for (const [i,type] of ['ROAD','ENTRY','EXIT','SLOT','CROSSING','BUILDING','CAMERA','BARRIER','SENSOR'].entries()) {
   await page.locator(`[data-tool=${type}]`).click();
   const cell=page.locator(`.grid [data-x="${i}"][data-y="0"]`);
   await cell.click();
   assert((await cell.getAttribute('class')).split(' ').includes(type));
   placed.push(await cell.getAttribute('data-cell'));
  }
  assert.equal(new Set(placed).size,9);
  await page.locator('[data-action=undo]').click();
  assert.equal(await page.locator('.grid [data-x="8"][data-y="0"]').getAttribute('data-cell'),null);
  await page.locator('[data-action=redo]').click();
  await page.locator('[data-action=saveLayout]').click();
  await page.waitForFunction(()=>document.querySelector('.canvas-toolbar')?.textContent.includes('บันทึกแล้ว'));
  await page.reload();
  await page.locator('[data-action=editSite]').first().click();
  for (const [i,id] of placed.entries()) assert.equal(await page.locator(`.grid [data-x="${i}"][data-y="0"]`).getAttribute('data-cell'),id);
  await page.screenshot({animations:'disabled',path:path.join(tmp,'editor-http-placement.png'),fullPage:true});
  // Remove isolated test pieces before publishing the existing valid layout.
  await page.locator('[data-tool=ERASE]').click();
  for (let i=0;i<9;i++) await page.locator(`.grid [data-x="${i}"][data-y="0"]`).click();
  await page.locator('[data-action=publish]').click();
  await page.locator('#notice').filter({hasText:'เผยแพร่ผังแล้ว'}).waitFor();
  await page.locator('[data-nav=operations]').click();
  await page.locator('[data-action=checkin]').click();
  await page.locator('#modal [name=plate]').fill('BROWSER-01');
  await page.locator('#modal [name=slotId]').selectOption('A4');
  await page.locator('#modal button[type=submit]').click();
  await page.locator('#modal').waitFor({state:'hidden'});
  assert(await page.locator('tbody').innerText().then(t=>t.includes('BROWSER-01')));
  // The main dashboard shares this session, site state, and ledger with the editor.
  await page.goto('http://localhost:8080/dashboard.html');
  await page.locator('#workspace').waitFor({state:'visible'});
  assert((await page.locator('#slotsGrid').innerText()).includes('BROWSER-01'));
  assert((await page.locator('.brand-title').innerText()).includes('Smart Parking System'));
  assert((await page.locator('#displayBoardMessage').innerText()).includes('ว่าง'));
  const tab=async name=>page.locator(`.tab-btn[onclick="switchTab('${name}')"]`).click();
  await page.screenshot({animations:'disabled',path:path.join(tmp,'dashboard-reference-desktop.png'),fullPage:true});
  await page.locator('[data-slot=A6]').click();
  await page.locator('[data-park=A6]').click();
  await page.locator('#licensePlate').fill('UI-ENTRY');
  await page.locator('#btnIssueTicket').click();
  await page.locator('#ticketModalOverlay.active').waitFor();
  assert((await page.locator('#modalSlot').innerText()).includes('A-6'));
  await page.locator('#ticketModalOverlay .modal-close-btn').click();
  await tab('lot-view');
  assert((await page.locator('#slotsGrid').innerText()).includes('UI-ENTRY'));
  await tab('exit-cashier');
  await page.locator('#exitSearchQuery').fill('BROWSER-01');
  await page.locator('button[onclick="searchTicketForExit()"] ').click();
  await page.locator('#feeResultCard').waitFor({state:'visible'});
  await page.locator('#paymentConfirmed').check();
  await page.locator('button[onclick="submitPayment()"] ').click();
  await page.locator('#receiptModalOverlay.active').waitFor();
  assert((await page.locator('#rcpPlate').innerText()).includes('BROWSER-01'));
  await page.locator('button[onclick="finishPaymentAndOpenExitGate()"] ').click();
  await page.locator('#notice').filter({hasText:'บันทึกรถออกแล้ว'}).waitFor();
  await tab('tickets-history');
  assert((await page.locator('#ticketsTableBody').innerText()).includes('BROWSER-01'));
  await tab('memberships');
  for(const [id,value]of Object.entries({memberId:'DASH-001',memberName:'Dashboard member',memberPlate:'DASH-MEMBER',memberRoom:'D101',memberFrom:'2026-01-01',memberUntil:'2030-12-31'}))await page.locator('#'+id).fill(value);
  await page.locator('form[onsubmit="createMembership(event)"] button').click();
  await page.locator('#membershipsList').getByText('Dashboard member',{exact:false}).waitFor();
  await tab('reservations');
  await page.locator('#reservationPlate').fill('DASH-BOOKING');
  await page.locator('#reservationSlot').selectOption('A4');
  await page.locator('#reservationStart').fill('2030-12-01T10:00');
  await page.locator('#reservationEnd').fill('2030-12-01T11:00');
  await page.locator('form[onsubmit="createReservation(event)"] button').click();
  await page.locator('#reservationsList').getByText('DASH-BOOKING').waitFor();
  await page.locator('[data-cancel]').click();
  await page.locator('#reservationsList').getByText('CANCELLED').waitFor();
  await tab('dashboard');
  assert((await page.locator('#dashboardMessage').innerText()).includes('รับชำระ 1'));
  await tab('ai-ops');
  await page.locator('#copilotInputText').fill('มีที่จอดว่างชั้นไหน');
  await page.locator('button[onclick="submitCopilotChat()"] ').click();
  await page.locator('#aiCopilotChatLog .chat-bubble.ai').filter({hasText:'ชั้น 1'}).waitFor();
  await tab('entry-gate');
  await page.locator('#licensePlate').fill('ANPR-TEST');
  await page.locator('#btnTriggerAnpr').click();
  await page.locator('#anprTargetText').filter({hasText:'จำลอง ANPR'}).waitFor();
  await tab('oop-docs');
  assert((await page.locator('#tab-oop-docs').innerText()).includes('OOP'));
  await tab('vehicle-history');
  const liveDownload=page.waitForEvent('download');await page.locator('#historyExportButton').click();
  await (await liveDownload).saveAs(path.join(tmp,'live-history.xlsx'));
  await page.setViewportSize({width:390,height:844});
  await tab('lot-view');
  await page.screenshot({animations:'disabled',path:path.join(tmp,'dashboard-reference-mobile.png'),fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  for(const mobileTab of ['entry-gate','exit-cashier','reservations','memberships','dashboard','ai-ops','oop-docs']){
    await tab(mobileTab);
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`mobile overflow: ${mobileTab}`);
  }
  await page.setViewportSize({width:1440,height:1000});
  await page.goto('http://localhost:8080/platform.html');
  await page.locator('#workspace').waitFor({state:'visible'});
  await page.locator('[data-action=openSite]').first().click();
  await page.locator('[data-nav=history]').click();
  const downloading=page.waitForEvent('download');
  await page.locator('[data-action=export]').click();
  const download=await downloading; await download.saveAs(path.join(tmp,'history.xlsx'));
  assert(fs.statSync(path.join(tmp,'history.xlsx')).size>1000);
  await page.locator('[data-nav=sites]').click();
  await page.locator('[data-action=createSite]').click();
  await page.locator('#modal [name=name]').fill('Browser custom');
  await page.locator('#modal [name=businessType]').selectOption('CUSTOM');
  await page.locator('#modal button[type=submit]').click();
  await page.locator('#modal').waitFor({state:'hidden'});
  for(const [type,x,y]of [['ENTRY',0,0],['ROAD',1,0],['EXIT',2,0],['SLOT',1,1]]){
   await page.locator(`[data-tool=${type}]`).click();
   await page.locator(`.cell[data-x="${x}"][data-y="${y}"]`).click();
  }
  await page.locator('[data-action=publish]').click();
  await page.locator('#notice').filter({hasText:'เผยแพร่ผังแล้ว'}).waitFor();
  await page.screenshot({animations:'disabled',path:path.join(tmp,'platform-editor.png'),fullPage:true});
  for(const nav of ['members','devices','settings','users','audit'])await page.locator(`[data-nav=${nav}]`).click();
  await page.locator('[data-nav=settings]').click();
  await page.locator('[data-action=pricing]').click();
  await page.locator('#modal [name=memberDiscountPercent]').fill('50');
  await page.locator('#modal [name=roomQuota]').fill('2');
  await page.locator('#modal button[type=submit]').click();
  await page.locator('#modal').waitFor({state:'hidden'});
  await page.locator('[data-nav=members]').click();
  assert((await page.locator('#main').innerText()).includes('50%'));
  await page.locator('[data-nav=editor]').click();
  await page.locator('[data-action=roadCurve]').click();
  await page.locator('#modal [name=label]').fill('Test curved road');
  await page.locator('#modal button[type=submit]').click();
  await page.locator('#modal').waitFor({state:'hidden'});
  assert.equal(await page.locator('svg[aria-label="แบบร่างถนนโค้ง"] path').count(),2);
  await page.setViewportSize({width:390,height:844});
  await page.locator('[data-nav=sites]').click();
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({animations:'disabled',path:path.join(tmp,'platform-mobile.png'),fullPage:true});
  await page.locator('#logoutButton').click();
  await page.locator('#loginScreen').waitFor({state:'visible'});
  await page.locator('#loginForm [name=username]').fill('staff');
  await page.locator('#loginForm [name=password]').fill('DemoPass123!');
  await page.locator('#loginForm button[type=submit]').click();
  await page.locator('#workspace').waitFor({state:'visible'});
  assert.equal(await page.locator('[data-nav=editor]').count(),0);
  assert.equal(await page.locator('[data-nav=history]').count(),0);
  await page.goto('http://localhost:8080/dashboard.html');
  await page.locator('#workspace').waitFor({state:'visible'});
  assert.equal(await page.locator('#sitePicker option').count(),1);
  assert.equal(await page.locator(".tab-btn[onclick=\"switchTab('vehicle-history')\"]").isVisible(),false);
  assert.equal(await page.locator('#historyExportButton').isVisible(),false);
  await page.goto('http://localhost:8080/platform.html');
  await page.locator('#workspace').waitFor({state:'visible'});
  await page.getByRole('button',{name:'เปลี่ยนรหัสผ่าน',exact:true}).click();
  await page.locator('#modal [name=currentPassword]').fill('DemoPass123!');
  await page.locator('#modal [name=newPassword]').fill('BrowserPassword123!');
  await page.locator('#modal [name=confirmPassword]').fill('BrowserPassword123!');
  await page.locator('#modal button[type=submit]').click();
  await page.locator('#loginScreen').waitFor({state:'visible'});
  await page.locator('#loginForm [name=username]').fill('staff');
  await page.locator('#loginForm [name=password]').fill('BrowserPassword123!');
  await page.locator('#loginForm button[type=submit]').click();
  await page.locator('#workspace').waitFor({state:'visible'});
  assert.deepEqual(errors,[]);
  const onboardingDir=path.join(tmp,'production-onboarding');
  fs.mkdirSync(onboardingDir); fs.symlinkSync(path.resolve('web'),path.join(onboardingDir,'web'),'dir');
  onboardingServer=spawn('java',['-cp',classes,'server.ParkingServer'],{cwd:onboardingDir,env:{...process.env,PORT:'8081',PLATFORM_ONLY:'true',PLATFORM_DEMO:'false',PLATFORM_ADMIN_PASSWORD:'SandboxPassword123!',PLATFORM_DATA_DIR:path.join(onboardingDir,'platform')},stdio:'ignore'});
  for(let i=0;i<100;i++){try{const r=await fetch('http://localhost:8081/api/platform/health');if(r.ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  const onboarding=await browser.newPage(); onboarding.on('dialog',dialog=>dialog.accept());
  await onboarding.goto('http://localhost:8081/');
  assert(onboarding.url().endsWith('/dashboard.html'));
  await onboarding.goto('http://localhost:8081/platform.html');
  await onboarding.locator('#loginForm [name=username]').fill('superadmin');
  await onboarding.locator('#loginForm [name=password]').fill('SandboxPassword123!');
  await onboarding.locator('#loginForm button[type=submit]').click();
  await onboarding.locator('#analyticsDays').waitFor();
  await onboarding.locator('#analyticsDays').selectOption('7');
  assert((await onboarding.locator('#main').innerText()).includes('ยังไม่มีลูกค้าจริง'));
  await onboarding.screenshot({path:'browser-artifacts/platform-owner-analytics.png',fullPage:true});
  await onboarding.locator('[data-nav=customers]').click();
  await onboarding.locator('[data-action=tenant]').click();
  await onboarding.locator('#modal [name=name]').fill('Disposable customer');
  await onboarding.locator('#modal [name=username]').fill('disposable-owner');
  await onboarding.locator('#modal [name=password]').fill('CustomerPassword123!');
  await onboarding.locator('#modal button[type=submit]').click();
  await onboarding.locator('#modal').waitFor({state:'hidden'});
  const disposable=onboarding.locator('tr').filter({hasText:'Disposable customer'});
  assert(await disposable.locator('[data-action=deleteTenant]').isDisabled());
  await disposable.locator('[data-action=toggleTenant]').click();
  await disposable.locator('[data-action=toggleTenant]').filter({hasText:'เปิดใช้งานกลับ'}).waitFor();
  await disposable.locator('[data-action=toggleTenant]').click();
  await disposable.locator('[data-action=toggleTenant]').filter({hasText:'ระงับการใช้งาน'}).waitFor();
  await disposable.locator('[data-action=toggleTenant]').click();
  await disposable.locator('[data-action=deleteTenant]:enabled').waitFor();
  await disposable.locator('[data-action=deleteTenant]').click();
  await onboarding.locator('#modal [name=confirmationName]').fill('Disposable customer');
  await onboarding.locator('#modal [name=currentPassword]').fill('SandboxPassword123!');
  await onboarding.locator('#modal button[type=submit]').click();
  await onboarding.locator('#modal').waitFor({state:'hidden'});
  assert.equal(await onboarding.locator('tr').filter({hasText:'Disposable customer'}).count(),0);
  await onboarding.locator('[data-action=sampleWorkspace]').waitFor();
  await onboarding.locator('[data-action=sampleWorkspace]').click();
  await onboarding.locator('#main .grid').waitFor();
  assert.equal(await onboarding.locator('#main .cell.SLOT').count(),20);
  await onboarding.locator('#floorPicker').selectOption('2');
  assert.equal(await onboarding.locator('#main .cell.SLOT').count(),20);
  await onboarding.locator('[data-nav=sites]').click();
  assert.equal(await onboarding.locator('.cards .card').count(),3);
  await onboarding.locator('[data-nav=history]').click();
  assert((await onboarding.locator('#main').innerText()).includes('ตัวอย่าง-'));
  await onboarding.locator('#backToCustomers').click();
  await onboarding.locator('[data-action=tenant]').click();
  await onboarding.locator('#modal [name=name]').fill('Isolated customer');
  await onboarding.locator('#modal [name=username]').fill('isolated-owner');
  await onboarding.locator('#modal [name=password]').fill('CustomerPassword123!');
  await onboarding.locator('#modal button[type=submit]').click();
  await onboarding.locator('#modal').waitFor({state:'hidden'});
  await onboarding.locator('[data-nav=analytics]').click();
  assert((await onboarding.locator('#main').innerText()).includes('Isolated customer'));
  await onboarding.locator('#analyticsDays').selectOption('90');
  await onboarding.screenshot({path:'browser-artifacts/platform-owner-analytics-desktop.png',fullPage:true});
  await onboarding.setViewportSize({width:390,height:844});
  await onboarding.screenshot({path:'browser-artifacts/platform-owner-analytics-mobile.png',fullPage:true});
  await onboarding.setViewportSize({width:1280,height:900});
  await onboarding.locator('[data-nav=customers]').click();
  const customerRow=onboarding.locator('tr').filter({hasText:'Isolated customer'});
  await customerRow.locator('[data-action=enterTenant]').click();
  assert.equal(await onboarding.locator('.cards .card').count(),0);
  assert.equal(await onboarding.locator('#tenantContext').innerText(),'Isolated customer');
  await onboarding.locator('[data-action=createSite]').click();
  await onboarding.locator('#modal [name=name]').fill('Private customer lot');
  await onboarding.locator('#modal button[type=submit]').click();
  await onboarding.locator('#modal').waitFor({state:'hidden'});
  const dashboardLink=await onboarding.locator('a[href^="dashboard.html?"]').first().getAttribute('href');
  await onboarding.goto('http://localhost:8081/'+dashboardLink);
  await onboarding.locator('#workspace').waitFor({state:'visible'});
  assert.equal(await onboarding.locator('#sitePicker option').count(),1);
  assert((await onboarding.locator('#account').innerText()).includes('Isolated customer'));
  await onboarding.goto('http://localhost:8081/platform.html');
  await onboarding.locator('#logoutButton').click();
  await onboarding.locator('#loginForm [name=username]').fill('isolated-owner');
  await onboarding.locator('#loginForm [name=password]').fill('CustomerPassword123!');
  await onboarding.locator('#loginForm button[type=submit]').click();
  await onboarding.locator('#workspace').waitFor({state:'visible'});
  assert.equal(await onboarding.locator('[data-nav=customers]').count(),0);
  assert.equal(await onboarding.locator('[data-action=tenant]').count(),0);
  assert.equal(await onboarding.locator('#sitePicker option').count(),1);
  assert(!(await onboarding.locator('#main').innerText()).includes('Green Residence'));
  await onboarding.locator('[data-nav=support]').click();
  await onboarding.locator('[data-action=createSupport]').click();
  await onboarding.locator('#modal [name=subject]').fill('Cannot edit parking <script>');
  await onboarding.locator('#modal [name=message]').fill('Open editor then save. Please investigate.');
  await onboarding.locator('#modal button[type=submit]').click();
  await onboarding.locator('#modal').waitFor({state:'hidden'});
  assert((await onboarding.locator('#main').innerText()).includes('Cannot edit parking <script>'));
  const supportOperator=await browser.newPage();
  await supportOperator.goto('http://localhost:8081/platform.html');
  await supportOperator.locator('#loginForm [name=username]').fill('superadmin');
  await supportOperator.locator('#loginForm [name=password]').fill('SandboxPassword123!');
  await supportOperator.locator('#loginForm button[type=submit]').click();
  await supportOperator.locator('[data-nav=support]').click();
  await supportOperator.locator('[data-action=replySupport]').click();
  await supportOperator.locator('#modal [name=message]').fill('We are investigating.');
  await supportOperator.locator('#modal button[type=submit]').click();
  await supportOperator.locator('#modal').waitFor({state:'hidden'});
  await supportOperator.locator('[data-action=supportStatus]').click();
  await supportOperator.locator('#modal [name=status]').selectOption('IN_PROGRESS');
  await supportOperator.locator('#modal button[type=submit]').click();
  await supportOperator.locator('#modal').waitFor({state:'hidden'});
  await supportOperator.locator('#main details summary').click();
  await supportOperator.screenshot({path:'browser-artifacts/platform-support.png',fullPage:true});
  await supportOperator.locator('[data-nav=billing]').click();
  await supportOperator.locator('[data-action=billingSettings]').click();
  await supportOperator.locator('#modal [name=paymentInstructions]').fill('TEST BANK — demonstration account only');
  await supportOperator.locator('#modal button[type=submit]').click();
  await supportOperator.locator('#modal').waitFor({state:'hidden'});
  await supportOperator.locator('[data-action=issueInvoice]').click();
  await supportOperator.locator('#modal [name=plan]').selectOption('STARTER');
  await supportOperator.locator('#modal button[type=submit]').click();
  await supportOperator.locator('#modal').waitFor({state:'hidden'});
  await onboarding.locator('#refreshButton').click();
  await onboarding.locator('[data-nav=billing]').click();
  await onboarding.locator('[data-action=reportTransfer]').click();
  await onboarding.locator('#modal [name=reference]').fill('customer-transfer-001');
  await onboarding.locator('#modal button[type=submit]').click();
  await onboarding.locator('#modal').waitFor({state:'hidden'});
  await supportOperator.locator('#refreshButton').click();
  await supportOperator.locator('#main .tag').filter({hasText:'แจ้งโอน / รอตรวจสอบ'}).waitFor();
  await supportOperator.locator('[data-action=confirmInvoice]').click();
  await supportOperator.locator('#modal [name=reference]').fill('bank-statement-001');
  await supportOperator.locator('#modal [name=confirmed]').check();
  await supportOperator.locator('#modal button[type=submit]').click();
  await supportOperator.locator('#modal').waitFor({state:'hidden'});
  await supportOperator.locator('#main .tag').filter({hasText:'รับเงินแล้ว'}).waitFor();
  await supportOperator.screenshot({path:'browser-artifacts/platform-billing-desktop.png',fullPage:true});
  await supportOperator.setViewportSize({width:390,height:844});
  assert(await supportOperator.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await supportOperator.screenshot({path:'browser-artifacts/platform-billing-mobile.png',fullPage:true});
  await onboarding.locator('[data-nav=support]').click();
  await supportOperator.close();
  await onboarding.locator('#refreshButton').click();
  await onboarding.locator('.support-message p').filter({hasText:'We are investigating.'}).waitFor({state:'attached'});
  await onboarding.locator('#main details summary').click();
  assert((await onboarding.locator('#main').innerText()).includes('We are investigating.'));
  await onboarding.locator('[data-nav=users]').click();
  assert((await onboarding.locator('#main').innerText()).includes('isolated-owner'));
  assert(!(await onboarding.locator('#main').innerText()).includes('superadmin'));
  await onboarding.goto('http://localhost:8081/dashboard.html');
  await onboarding.locator('#workspace').waitFor({state:'visible'});
  await onboarding.locator('#startPresentation').click();
  await onboarding.locator('#presentationGuide').waitFor({state:'visible'});
  const demoTab=async name=>onboarding.locator(`.tab-btn[onclick="switchTab('${name}')"]`).click();
  await demoTab('entry-gate');
  await onboarding.locator('[name=vType][value=TRUCK]').check({force:true});
  await onboarding.evaluate(()=>updateVehicleSelection());
  await onboarding.locator('#btnTriggerAnpr').click();
  await onboarding.locator('#anprTargetText').filter({hasText:'จำลอง ANPR'}).waitFor();
  const truckPlate=await onboarding.locator('#licensePlate').inputValue();
  assert(truckPlate.startsWith('DEMO-'));
  assert((await onboarding.locator('#aiRecSlotBadge').innerText()).includes('A-20'));
  await onboarding.locator('#btnIssueTicket').click();
  await onboarding.locator('#ticketModalOverlay.active').waitFor();
  await onboarding.locator('#ticketModalOverlay .modal-close-btn').click();
  await onboarding.locator('#clockController button[onclick="fastForward(60)"]').click();
  await demoTab('exit-cashier');
  await onboarding.locator('#exitSearchQuery').fill(truckPlate);
  await onboarding.locator('button[onclick="searchTicketForExit()"] ').click();
  await onboarding.locator('#feeResultCard').waitFor({state:'visible'});
  await onboarding.locator('#simulatePayment').click();
  await onboarding.locator('#receiptModalOverlay.active').waitFor();
  assert((await onboarding.locator('#receiptModalOverlay').innerText()).includes('SIMULATED_CASH'));
  await onboarding.locator('button[onclick="finishPaymentAndOpenExitGate()"] ').click();
  await onboarding.locator('#receiptModalOverlay').waitFor({state:'hidden'});
  await demoTab('lot-view');
  await onboarding.screenshot({animations:'disabled',path:path.join(tmp,'studio-dashboard-desktop.png'),fullPage:true});
  await onboarding.locator('#resetPresentation').click();
  await onboarding.locator('#notice').filter({hasText:'พร้อมเริ่มสาธิตรอบใหม่'}).waitFor();
  assert.equal(await onboarding.locator('#headerOccCount').innerText(),'0');
  await onboarding.setViewportSize({width:390,height:844});
  await onboarding.screenshot({animations:'disabled',path:path.join(tmp,'studio-dashboard-mobile.png'),fullPage:true});
  assert(await onboarding.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await onboarding.locator('#logout').click();
  await onboarding.locator('#loginPanel').waitFor({state:'visible'});
  await onboarding.screenshot({animations:'disabled',path:path.join(tmp,'studio-login-mobile.png'),fullPage:true});
  assert(await onboarding.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  console.log('Browser PASS: shared dashboard session/ledger, parking, cash checkout, XLSX, custom road layout, all tabs, mobile, staff permissions');
  console.log('QA artifacts: '+tmp);
 } finally {if(process.env.CI){fs.mkdirSync('browser-artifacts',{recursive:true});for(const name of fs.readdirSync(tmp).filter(n=>n.endsWith('.png')))fs.copyFileSync(path.join(tmp,name),path.join('browser-artifacts',name));}if(browser)await browser.close();server.kill('SIGTERM');if(onboardingServer)onboardingServer.kill('SIGTERM');}
})().catch(e=>{console.error(e);process.exitCode=1;});
